name: Go Build (Linux)

on:
  push:
    branches:
      - main
  workflow_dispatch:  # pozwala uruchamiać ręcznie w Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build client and host
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/client ./cmd/client
          GOOS=linux GOARCH=amd64 go build -o dist/host ./cmd/host

      - name: Check files (DEBUG)
        run: ls -lah dist